# fly.toml app configuration file generated for megaqc-trino on 2025-05-10T13:56:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'megaqc-trino'
primary_region = 'mad'

[build]

[env]
AWS_REGION = 'eu-central-1'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 250
soft_limit = 200

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
